name: Daily rewards executable
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '57 18 * * *'
jobs:
  Run-On-MacOS:
    runs-on: macos-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      - 
        name: setup-docker
        run: |
           brew install docker
           colima start
      -  
        name: run-docker
        env:
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFTEMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFTPASSWORD }}
          TELEGRAM_API: ${{ secrets.TELEGRAMAPI }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAMUSERID }}
        run: |
          docker run -it --rm --volume ./mount:/opt/wd --name undetected-chromedriver -e VNC_PASSWORD=123456 -e MICROSOFT_EMAIL="$MICROSOFT_EMAIL" -e MICROSOFT_PASSWORD="$MICROSOFT_PASSWORD" -e TELEGRAM_API="$TELEGRAM_API" -e TELEGRAM_USERID="$telegramUSERID" -p 5900:5900 dx5594206/uc-docker:latest python script-workflow/bing-rewards/BingRewards/BingRewards.py -nhl -t -c
          docker run -it --rm --volume ./mount:/opt/wd --name undetected-chromedriver -e VNC_PASSWORD=123456 -e MICROSOFT_EMAIL="$MICROSOFT_EMAIL" -e MICROSOFT_PASSWORD="$MICROSOFT_PASSWORD" -e TELEGRAM_API="$TELEGRAM_API" -e TELEGRAM_USERID="$telegramUSERID" -p 5900:5900 dx5594206/uc-docker:latest python script-workflow/bing-rewards/BingRewards/BingRewards.py -nhl -t -c
          
